name: Move linked issue to "In Review" (Projects v2)

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  move-issue-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to "In Review"
        uses: titoportas/update-project-fields@v2
        with:
          github-token: ${{ secrets.ORG_PAT }}
          organization: 365Soft-Bolivia
          project-number: 1               # <- es el nÃºmero que aparece en tu URL (/projects/1/)
          item-id: ${{ github.event.pull_request.node_id }}
          field: Status                   # <- nombre del campo (columna) en tu project
          value: "In review"              # <- el valor exacto del campo (columna)
